on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '12.x'
      
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run backup --if-present
    - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cards-bak
          path: |
            src/cards-bak.json
